version: '2'
services:
  zookeeper:
    image: "wurstmeister/zookeeper:latest"
    ports:
    - "2181:2181"
  kafka:
    image: "wurstmeister/kafka:2.12-2.1.0"
    links:
    - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "127.0.0.1"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    ports:
    - "9092:9092"
