version: "3"
services:
  prometheus:
    image: prom-accor-dev:0.0.1
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
    ports:
    - 9200:9090
  grafana:
    image: grafana/grafana
    ports:
    - 9300:3000
    #   volumes:
    #   - ./grafana/provisioning/:/etc/grafana/provisioning/
    depends_on:
    - prometheus