global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.

  external_labels:
    monitor: 'admin-event-stream'

rule_files:

scrape_configs:
- job_name: 'prometheus'
  scrape_interval: 5s
  static_configs:
  - targets: ['localhost:9090']
- job_name: "node"
  scrape_interval: "15s"
  metrics_path: /management/prometheus
  static_configs:
  - targets:
      - W-PCOPPOLINO.eu.accor.net:9091